### ISSUE TITLE
Remove unnecessary comments

### ISSUE THREAD

**Issue by adityaraute** [agriyakhetarpal/LorenzChaosEncryption#1]
The Code files have a lot of unnecessary comments, which are I think different approach for running the code. I'd suggest getting rid of those things. Could also be a good first issue.

Also, how do I run this project? Maybe add a link to Colab notebook or repl.it or whatever you are comfortable with.

**Comment by agriyakhetarpal** [comment]
I added the comments to explain to the user what the code does. Could you tell me which ones are not needed exactly? I'll remove them. I haven't made a Colab notebook for the project yet but, sure

**Comment by adityaraute** [comment]
In [this](https://github.com/agriyakhetarpal/LorenzChaosEncryption/blob/master/Lorenz%20encryption/lorenzEncryption.py) file, I don't think the commented code after 95th line might be unnecessary.

**Comment by agriyakhetarpal** [comment]
Yes, that's for decrypting the image, but unfortunately, I wasn't able to get it to work in the stipulated time of the project – it's reserved as a work-in-progress :)

**Comment by adityaraute** [comment]
Oh okay, that's fair then. Would recommend having that on another branch though, so you can merge it once done.

**Comment by agriyakhetarpal** [comment]
Thanks for the tips!
